import type { AccentColor } from '@/config/type'

// Tailwind class maps — all classes must appear literally so the scanner includes them
export const ACCENT = {
  rose: {
    badge: 'bg-rose-50 text-rose-600 border-rose-100',
    highlight: 'text-rose-600',
    button: 'bg-rose-600 hover:bg-rose-700 text-white',
    buttonOutline: 'border-slate-200 text-slate-700 hover:bg-slate-50',
    buttonInverted: 'bg-white text-rose-600 hover:bg-rose-50',
    highlightPlan: 'bg-rose-600 border-rose-600 text-white shadow-lg shadow-rose-100',
    check: 'text-rose-500',
    checkInverted: 'text-rose-200',
    featureBorder: 'hover:border-rose-200',
    progressBar: 'bg-rose-500',
    link: 'text-rose-600 hover:text-rose-700',
  },
  violet: {
    badge: 'bg-violet-50 text-violet-600 border-violet-100',
    highlight: 'text-violet-600',
    button: 'bg-violet-600 hover:bg-violet-700 text-white',
    buttonOutline: 'border-slate-200 text-slate-700 hover:bg-slate-50',
    buttonInverted: 'bg-white text-violet-600 hover:bg-violet-50',
    highlightPlan: 'bg-violet-600 border-violet-600 text-white shadow-lg shadow-violet-100',
    check: 'text-violet-500',
    checkInverted: 'text-violet-200',
    featureBorder: 'hover:border-violet-200',
    progressBar: 'bg-violet-500',
    link: 'text-violet-600 hover:text-violet-700',
  },
  blue: {
    badge: 'bg-blue-50 text-blue-600 border-blue-100',
    highlight: 'text-blue-600',
    button: 'bg-blue-600 hover:bg-blue-700 text-white',
    buttonOutline: 'border-slate-200 text-slate-700 hover:bg-slate-50',
    buttonInverted: 'bg-white text-blue-600 hover:bg-blue-50',
    highlightPlan: 'bg-blue-600 border-blue-600 text-white shadow-lg shadow-blue-100',
    check: 'text-blue-500',
    checkInverted: 'text-blue-200',
    featureBorder: 'hover:border-blue-200',
    progressBar: 'bg-blue-500',
    link: 'text-blue-600 hover:text-blue-700',
  },
  emerald: {
    badge: 'bg-emerald-50 text-emerald-600 border-emerald-100',
    highlight: 'text-emerald-600',
    button: 'bg-emerald-600 hover:bg-emerald-700 text-white',
    buttonOutline: 'border-slate-200 text-slate-700 hover:bg-slate-50',
    buttonInverted: 'bg-white text-emerald-600 hover:bg-emerald-50',
    highlightPlan: 'bg-emerald-600 border-emerald-600 text-white shadow-lg shadow-emerald-100',
    check: 'text-emerald-500',
    checkInverted: 'text-emerald-200',
    featureBorder: 'hover:border-emerald-200',
    progressBar: 'bg-emerald-500',
    link: 'text-emerald-600 hover:text-emerald-700',
  },
  orange: {
    badge: 'bg-orange-50 text-orange-600 border-orange-100',
    highlight: 'text-orange-600',
    button: 'bg-orange-600 hover:bg-orange-700 text-white',
    buttonOutline: 'border-slate-200 text-slate-700 hover:bg-slate-50',
    buttonInverted: 'bg-white text-orange-600 hover:bg-orange-50',
    highlightPlan: 'bg-orange-600 border-orange-600 text-white shadow-lg shadow-orange-100',
    check: 'text-orange-500',
    checkInverted: 'text-orange-200',
    featureBorder: 'hover:border-orange-200',
    progressBar: 'bg-orange-500',
    link: 'text-orange-600 hover:text-orange-700',
  },
  amber: {
    badge: 'bg-amber-50 text-amber-600 border-amber-100',
    highlight: 'text-amber-600',
    button: 'bg-amber-500 hover:bg-amber-600 text-white',
    buttonOutline: 'border-slate-200 text-slate-700 hover:bg-slate-50',
    buttonInverted: 'bg-white text-amber-600 hover:bg-amber-50',
    highlightPlan: 'bg-amber-500 border-amber-500 text-white shadow-lg shadow-amber-100',
    check: 'text-amber-500',
    checkInverted: 'text-amber-200',
    featureBorder: 'hover:border-amber-200',
    progressBar: 'bg-amber-500',
    link: 'text-amber-600 hover:text-amber-700',
  },
  pink: {
    badge: 'bg-pink-50 text-pink-600 border-pink-100',
    highlight: 'text-pink-600',
    button: 'bg-pink-600 hover:bg-pink-700 text-white',
    buttonOutline: 'border-slate-200 text-slate-700 hover:bg-slate-50',
    buttonInverted: 'bg-white text-pink-600 hover:bg-pink-50',
    highlightPlan: 'bg-pink-600 border-pink-600 text-white shadow-lg shadow-pink-100',
    check: 'text-pink-500',
    checkInverted: 'text-pink-200',
    featureBorder: 'hover:border-pink-200',
    progressBar: 'bg-pink-500',
    link: 'text-pink-600 hover:text-pink-700',
  },
  indigo: {
    badge: 'bg-indigo-50 text-indigo-600 border-indigo-100',
    highlight: 'text-indigo-600',
    button: 'bg-indigo-600 hover:bg-indigo-700 text-white',
    buttonOutline: 'border-slate-200 text-slate-700 hover:bg-slate-50',
    buttonInverted: 'bg-white text-indigo-600 hover:bg-indigo-50',
    highlightPlan: 'bg-indigo-600 border-indigo-600 text-white shadow-lg shadow-indigo-100',
    check: 'text-indigo-500',
    checkInverted: 'text-indigo-200',
    featureBorder: 'hover:border-indigo-200',
    progressBar: 'bg-indigo-500',
    link: 'text-indigo-600 hover:text-indigo-700',
  },
} satisfies Record<AccentColor, Record<string, string>>

export type AccentClasses = (typeof ACCENT)[AccentColor]

export function getAccent(color: AccentColor): AccentClasses {
  return ACCENT[color] ?? ACCENT.rose
}
