import type { GoogleAdsOverride } from '../lib/google-ads/type'

export const GOOGLE_ADS_SEARCH_FIT_RULES = [
  'SEO keywords contain commercial-intent terms such as software, tool, automation, delivery, recovery, or record.',
  'The landing targets a clear buyer segment instead of a broad lifestyle audience.',
  'The pain point is expensive, urgent, or operationally repetitive enough for paid search.',
  'The page has paid tiers or a clear monetization path beyond a generic waitlist.',
] as const

export const GOOGLE_ADS_DEFAULT_NEGATIVE_KEYWORDS = [
  'free',
  'template',
  'templates',
  'example',
  'examples',
  'job',
  'jobs',
  'salary',
  'course',
  'training',
  'pdf',
  'ppt',
  'download',
] as const

export const GOOGLE_ADS_OVERRIDES: Record<string, GoogleAdsOverride> = {
  slotfill: {
    valueProposition: 'Automatically fill cancelled appointments from your waitlist in seconds.',
    targetCustomer: 'Salons, clinics, gyms, and appointment-based service businesses.',
    painPoint: 'No-shows and last-minute cancellations leave revenue on the table and manual waitlist follow-up is too slow.',
    keywordIntent: 'no-show recovery software',
    audienceLabel: 'Salons & Clinics',
    adGroupName: 'slotfill_no_show_recovery',
    keywordSeeds: [
      'no-show recovery software',
      'appointment waitlist software',
      'fill cancelled appointments',
      'appointment cancellation software',
      'auto fill cancellations',
      'rebook cancelled appointments',
      'salon waitlist software',
      'clinic waitlist software',
      'appointment slot recovery',
      'last minute cancellation software',
    ],
    negativeKeywords: ['policy', 'letter', 'sample', 'script'],
    rsaHeadlines: [
      'Fill Cancelled Appointments',
      'No-Show Recovery Software',
      'Auto-Fill Last-Minute Slots',
      'SlotFill for Salons & Clinics',
      'Text Your Waitlist in Seconds',
      'Rebook Cancellations Faster',
      'First Click Gets the Slot',
      'See How SlotFill Works',
      'Join SlotFill Early Access',
      'Fill Open Slots in Minutes',
      'Stop Manual Waitlist Calls',
      'Recover More Missed Revenue',
      'Built for Appointment Teams',
      'Turn Empty Slots Into Bookings',
      'Waitlist Outreach on Autopilot',
    ],
    descriptions: [
      'When an appointment cancels, SlotFill texts your waitlist fast so the slot gets filled.',
      'Built for salons, clinics, gyms, and service businesses that lose money to no-shows.',
      'Replace manual calls and text chains with automatic outreach and first-click booking.',
      'Join the waitlist for early access and see if SlotFill can recover more missed revenue.',
    ],
    sitelinks: [
      {
        linkText: 'How SlotFill Works',
        description1: 'See the cancellation flow',
        description2: 'From open slot to rebooked',
      },
      {
        linkText: 'Join Early Access',
        description1: 'Get launch updates first',
        description2: 'Be first to test SlotFill',
        path: '#waitlist',
      },
      {
        linkText: 'For Salons & Clinics',
        description1: 'Built for booked services',
        description2: 'Great for small teams',
      },
      {
        linkText: 'Revenue Recovery',
        description1: 'Recover missed bookings',
        description2: 'Reduce empty chair time',
      },
    ],
    callouts: [
      'Fill Empty Slots Fast',
      'Waitlist Text Alerts',
      'First-Click Booking',
      'Less Manual Follow-Up',
      'Recover Missed Revenue',
      'For Salons & Clinics',
    ],
  },
  reportflow: {
    valueProposition: 'Generate and deliver branded client reports automatically on a schedule.',
    targetCustomer: 'Agencies and data teams that send recurring client reports.',
    painPoint: 'Manual PDF exports and broken report jobs waste hours every month.',
    keywordIntent: 'automated client reporting',
    audienceLabel: 'Agencies & Data Teams',
    adGroupName: 'reportflow_client_reports',
    keywordSeeds: [
      'automated client reporting',
      'client report automation',
      'white label reporting software',
      'scheduled report delivery',
      'automated marketing reports',
      'agency report automation',
      'white label pdf reports',
      'send client reports automatically',
      'report delivery software',
      'automated reports for agencies',
    ],
    negativeKeywords: ['looker studio tutorial', 'sample report', 'dashboard template'],
    calloutHints: ['Branded PDF Reports', 'Scheduled Delivery', 'No Manual Exports'],
    rsaHeadlines: [
      'Automated Client Reporting',
      'Stop Manual PDF Exports',
      'Reports That Send Themselves',
      'Branded Client Reports',
      'ReportFlow for Agencies',
      'Built for Data Agencies',
      'Connect any data source',
      'Branded report builder',
      'Auto-Scheduled Delivery',
      'No More Looker Hacks',
      'GA4 + Stripe in One PDF',
      'Save 5 Hours per Client',
      'Set Once. Schedule Forever.',
      'White-Label Client Reports',
      'Join ReportFlow Early Access',
    ],
    descriptions: [
      'Generate and deliver branded client reports automatically on a schedule.',
      'Built for marketing & data agencies. Connect GA4, Stripe, HubSpot — done.',
      'Stop manual PDF exports. ReportFlow sends every client report on time.',
      'Join the early access waitlist for launch updates and a beta-only price.',
    ],
  },
  declog: {
    valueProposition: 'Capture and search the why behind engineering decisions linked to GitHub PRs.',
    targetCustomer: 'CTOs, engineering managers, and software teams that lose architectural context.',
    painPoint: 'Teams keep re-asking why a decision was made because context is scattered across PRs, Slack, and memory.',
    keywordIntent: 'architecture decision record tool',
    audienceLabel: 'Engineering Teams',
    adGroupName: 'declog_adr_software',
    keywordSeeds: [
      'architecture decision record tool',
      'adr software',
      'engineering decision log',
      'architecture decision log',
      'technical decision tracking',
      'adr tool for engineering teams',
      'github adr tool',
      'decision log software',
      'software architecture decisions',
      'record technical decisions',
    ],
    negativeKeywords: ['markdown template', 'construction', 'residential'],
    calloutHints: ['GitHub Linked', 'Searchable ADRs', 'Faster Onboarding'],
  },
}
